# Generated by Django 5.0.7 on 2024-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('licence_plate', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('vin_number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='', upload_to='images')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
    ]
