# Generated by Django 5.0.7 on 2024-08-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
