# Generated by Django 5.0.7 on 2024-08-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('licence_plate', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('vin_number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='', upload_to='images')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('csv_file', models.FileField(default='', upload_to='files')),
                ('slug', models.SlugField(default='', unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.car')),
            ],
        ),
    ]
