# Generated by Django 5.0.7 on 2024-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_remove_measurement_problems_measurement_txt_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='csv_file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
